sudo: false
language: go
os:
  - linux
  - osx
go:
  - 1.11.x
install: go get -u github.com/golang/dep/cmd/dep && dep ensure && go build -o atreus-backend
script:
  - cd common/auth && go test && cd ../../
after_success:
  - go test -v -covermode=count -coverprofile=coverage.out
    $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
before_deploy:
  - PLATFORMS=(darwin/amd64 linux/amd64)

  # build binary for all archs
  - |
    for PLATFORM in "${PLATFORMS[@]}"; do
      echo "Building $PLATFORM"
      GOOS=${PLATFORM%/*}
      GOARCH=${PLATFORM#*/}
      if [ "$GOOS" = "windows" ]; then
        build_cmd="GOOS=$GOOS GOARCH=$GOARCH go build -o atreus-backend -ldflags '-w -s'"
      else
        build_cmd="CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o atreus-backend"
      fi
      if ! eval $build_cmd; then
        echo "Failed building atreus-backend for $PLATFORM" && return 1
      fi
      if [ "$GOOS" = "windows" ]; then
        zip atreus-backend-${GOOS}-${GOARCH}.zip atreus-backend
      else
        tar cvzf atreus-backend-${GOOS}-${GOARCH}.tgz atreus-backend
      fi
    done
  - ls

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
    - "atreus-backend-darwin-amd64.tgz"
    - "atreus-backend-linux-amd64.tgz"

  skip_cleanup: true
  on:
    tags: true