sudo: false
language: go
os:
  - linux
  - osx
go:
  - 1.11.x
branches:
  only:
    - master
script:
  - cd common/auth && go test
after_success:
  - go test -v -covermode=count -coverprofile=coverage.out
    $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
